### ISSUE TITLE
Where are the checkpoints of your trained networks specially the encoder in stage 3?

### ISSUE THREAD

**Issue by EhabIbrahim758** [seva100/stylegan-for-facerec#2]

**Comment by seva100** [comment]
Hi @EhabIbrahim758, the checkpoints are [here](https://drive.google.com/drive/folders/1UDxqL5kyGnkncHGY2iq6b2J7pNIWmlET).

To access the data, please use the [Google form](https://forms.gle/kmbuvNgk6aDnNWaW8).

**Comment by EhabIbrahim758** [comment]
These checkpoints are for the encoder only ?
@seva100

**Comment by EhabIbrahim758** [comment]
Also After submitting the google form i found the google drive link but i don't have permission to open it so i need an access 
@seva100

**Comment by seva100** [comment]
@EhabIbrahim758 Yes, the checkpoints are for the encoder only.

I've added the sharing for the Google drive folder, please check one more time if it works. Thank you for pointing this out.

**Comment by EhabIbrahim758** [comment]
Solved Thank You
